import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

// Built output lands in the plugin's own `web/3d/`, which the EXISTING static route
// already serves — so the 3D view adds no new FastAPI route, and therefore does not need
// a process restart to appear (a new route would: FastAPI cannot swap a mounted router,
// which is documented at length in docs/HANDOFF.md).
//
// `base: "./"` is load-bearing. The page is served at
// `/plugins/bloodbowl/static/3d/index.html` on the host window and at
// `/agents/<slug>/plugins/bloodbowl/static/3d/index.html` through the fleet proxy;
// RELATIVE asset URLs resolve correctly under both, and an absolute base would break the
// proxy — which is the guide's rule 3 (never hardcode a base).
export default defineConfig({
  base: "./",
  plugins: [react()],
  // FIXED filenames, no content hash: the page addresses the bundle by name at runtime
  // (see index.html), so a hashed name would need a build-time rewrite of the HTML. The
  // trade-off is cache-busting, which does not apply here — the asset is served by the
  // plugin's own route with no long-lived cache headers.
  build: {
    outDir: "../web/3d",
    // The entry is the MODULE, not index.html: the shipped page is generated by
    // build-page.mjs so it can address the bundle by an absolute, base-derived URL at
    // runtime. Vite discovers entries from <script src> tags in an HTML entry, which is
    // exactly the relative reference this view cannot use.
    emptyOutDir: false,
    rollupOptions: {
      input: "src/main.jsx",
      output: { entryFileNames: "assets/app.js", chunkFileNames: "assets/[name].js", assetFileNames: "assets/[name][extname]" },
    },
  },
  server: { port: 5199, proxy: { "/api": { target: "http://127.0.0.1:7878", changeOrigin: true } } },
});
